import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {BrowserRouter,useNavigate,Routes,Route,Link} from 'react-router-dom'
import {BookOpen,Brain,LogOut,Upload,PlayCircle,MessageCircle,FileText,Layers,CheckCircle,Search} from 'lucide-react'
import api from './services/api'
import './styles.css'

function saveSession(data){localStorage.setItem('intellilearn_token',data.token);localStorage.setItem('intellilearn_user',JSON.stringify(data.user))}
function user(){try{return JSON.parse(localStorage.getItem('intellilearn_user')||'null')}catch{return null}}
function logout(){localStorage.removeItem('intellilearn_token');localStorage.removeItem('intellilearn_user');location.href='/login'}

function Layout({children}){
 const u=user(); const nav=useNavigate();
 return <div className="app-shell"><aside><div className="brand"><div className="logo"><Brain size={22}/></div><div><b>IntelliLearn</b><span>AI Academic Assistant</span></div></div><nav><Link to="/dashboard"><BookOpen/>Dashboard</Link>{u?.role==='faculty'&&<Link to="/faculty"><Upload/>Faculty Upload</Link>}<Link to="/youtube"><PlayCircle/>YouTube Learning</Link></nav><div className="side-bottom"><div className="user-card"><div className="avatar">{u?.name?.[0]?.toUpperCase()}</div><div><b>{u?.name}</b><small>{u?.role}</small></div></div><button className="ghost" onClick={()=>{logout();nav('/login')}}><LogOut size={17}/>Logout</button></div></aside><main>{children}</main></div>
}

function Auth({mode}){
 const [form,setForm]=useState({name:'',email:'',password:'',role:'student'}); const [error,setError]=useState(''); const nav=useNavigate();
 const submit=async e=>{e.preventDefault();setError('');try{const r=await api.post(`/auth/${mode}`,form);saveSession(r.data);nav('/dashboard')}catch(err){setError(err.response?.data?.error||'Something went wrong')}}
 return <div className="auth"><div className="auth-card"><div className="brand centered"><div className="logo"><Brain size={24}/></div><div><b>IntelliLearn AI</b><span>Learn from your academic material</span></div></div><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p className="muted">{mode==='login'?'Continue your learning journey.':'Register as a student or faculty member.'}</p><form onSubmit={submit}>{mode==='register'&&<input placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="password" placeholder="Password (6+ characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{mode==='register'&&<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="student">Student</option><option value="faculty">Faculty</option></select>}<button className="primary">{mode==='login'?'Login':'Register'}</button>{error&&<div className="error">{error}</div>}</form><p className="switch">{mode==='login'?<>New here? <Link to="/register">Create account</Link></>:<>Already registered? <Link to="/login">Login</Link></>}</p></div></div>
}

function Dashboard(){
 const [docs,setDocs]=useState([]);const [selected,setSelected]=useState(null);const [loading,setLoading]=useState(true);const u=user();
 useEffect(()=>{api.get('/documents').then(r=>setDocs(r.data.documents)).catch(()=>{}).finally(()=>setLoading(false))},[])
 return <Layout><div className="topbar"><div><span className="eyebrow">STUDENT WORKSPACE</span><h1>Academic Library</h1><p>Choose a faculty-provided resource and study with AI.</p></div>{u?.role==='faculty'&&<Link className="primary small" to="/faculty"><Upload size={17}/>Upload PDF</Link>}</div>{loading?<div className="empty">Loading resources...</div>:docs.length===0?<div className="empty"><FileText size={40}/><h2>No academic material yet</h2><p>Ask faculty to upload a PDF, or log in as faculty for the demo.</p></div>:<div className="resource-grid">{docs.map(d=><button className="resource-card" key={d.id} onClick={()=>setSelected(d)}><div className="file-icon"><FileText/></div><div className="resource-body"><span className="tag">{d.subject}</span><h3>{d.title}</h3><p>{d.unit||'Academic resource'} · Uploaded by {d.uploaded_by_name}</p></div></button>)}</div>}{selected&&<StudyPanel doc={selected} close={()=>setSelected(null)}/>}</Layout>
}

function StudyPanel({doc,close}){
 const [tab,setTab]=useState('chat');const [question,setQuestion]=useState('');const [messages,setMessages]=useState([]);const [answer,setAnswer]=useState('');const [busy,setBusy]=useState(false);const [material,setMaterial]=useState(null);
 useEffect(()=>{api.get(`/documents/${doc.id}/messages`).then(r=>setMessages(r.data.messages)).catch(()=>{})},[doc.id])
 const ask=async e=>{e?.preventDefault();if(!question.trim())return;setBusy(true);setAnswer('');try{const r=await api.post(`/documents/${doc.id}/chat`,{question});setMessages(m=>[...m,{role:'user',content:question},{role:'assistant',content:r.data.answer}]);setQuestion('');setAnswer(r.data.answer)}catch(err){setAnswer(err.response?.data?.error||'Unable to answer')}finally{setBusy(false)}}
 const generate=async kind=>{setBusy(true);setMaterial(null);try{const r=await api.post(`/documents/${doc.id}/generate/${kind}`);setMaterial(r.data.result)}catch(err){setMaterial({error:err.response?.data?.error||'Generation failed'})}finally{setBusy(false)}}
 return <div className="overlay"><div className="study-panel"><div className="panel-head"><div><span className="tag">{doc.subject}</span><h2>{doc.title}</h2></div><button className="close" onClick={close}>×</button></div><div className="tabs">{[['chat','Chat with PDF',MessageCircle],['summary','Summary',FileText],['flashcards','Flashcards',Layers],['quiz','Quiz',CheckCircle],['exam','10-Mark Answer',BookOpen]].map(([id,label,Icon])=><button className={tab===id?'active':''} onClick={()=>{setTab(id);setMaterial(null);if(id!=='chat')generate(id)}} key={id}><Icon size={16}/>{label}</button>)}</div><div className="panel-content">{tab==='chat'?<><div className="chat-list">{messages.length?messages.map((m,i)=><div className={`bubble ${m.role}`} key={i}><b>{m.role==='user'?'You':'IntelliLearn AI'}</b><div>{m.content}</div></div>):<div className="empty mini"><MessageCircle size={32}/><p>Ask anything about this PDF.</p></div>}{answer&&!messages.length&&<div className="bubble assistant"><b>IntelliLearn AI</b><div>{answer}</div></div>}</div><form className="chat-form" onSubmit={ask}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask a doubt from this PDF..."/><button className="primary" disabled={busy}>{busy?'Thinking...':'Ask'}</button></form></>:<Material result={material} busy={busy} type={tab}/>}</div></div></div>
}

function Material({result,busy,type}){if(busy)return <div className="empty mini">Generating {type}...</div>;if(!result)return <div className="empty mini">Choose a study tool above.</div>;if(result.error)return <div className="error">{result.error}</div>;if(type==='flashcards')return <div className="cards">{(result.flashcards||[]).map((x,i)=><div className="flash" key={i}><span>Card {i+1}</span><h3>{x.front}</h3><p>{x.back}</p></div>)}</div>;if(type==='quiz')return <div className="quiz">{(result.questions||[]).map((q,i)=><div className="quiz-q" key={i}><b>{i+1}. {q.question}</b>{q.options?.map((o,j)=><div className="option" key={j}>{String.fromCharCode(65+j)}. {o}</div>)}<small>Answer: {q.answer}</small><p>{q.explanation}</p></div>)}</div>;return <article className="markdown-like">{String(result).split('\n').map((line,i)=><p key={i}>{line||' '}</p>)}</article>}

function Faculty(){const [form,setForm]=useState({title:'',subject:'',unit:'',description:''});const [file,setFile]=useState(null);const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);const upload=async e=>{e.preventDefault();if(!file){setStatus('Choose a PDF first.');return}setBusy(true);setStatus('');const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.append(k,v));fd.append('file',file);try{const r=await api.post('/documents/upload',fd,{headers:{'Content-Type':'multipart/form-data'}});setStatus(`Uploaded successfully: ${r.data.pages} pages indexed into ${r.data.chunks} searchable chunks.`);setForm({title:'',subject:'',unit:'',description:''});setFile(null)}catch(err){setStatus(err.response?.data?.error||'Upload failed')}finally{setBusy(false)}};return <Layout><div className="topbar"><div><span className="eyebrow">FACULTY WORKSPACE</span><h1>Upload Academic Material</h1><p>Publish a PDF so students can chat with it and generate study material.</p></div></div><div className="upload-layout"><form className="upload-card" onSubmit={upload}><label>PDF file<input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Operating Systems Unit 2"/></label><label>Subject<input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="e.g. Operating Systems"/></label><label>Unit<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} placeholder="e.g. Unit 2"/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Short description for students"/></label><button className="primary" disabled={busy}><Upload size={18}/>{busy?'Processing PDF...':'Upload and Index PDF'}</button>{status&&<div className={status.startsWith('Uploaded')?'success':'error'}>{status}</div>}</form><div className="info-card"><h2>What happens after upload?</h2><ol><li>PDF text is extracted.</li><li>The text is split into smaller chunks.</li><li>Sentence embeddings are created.</li><li>A FAISS vector index is stored for this document.</li><li>Students can ask questions and generate study material from the retrieved content.</li></ol><div className="note">Version 1 supports text-based PDFs. Handwritten/scanned OCR is planned as future scope.</div></div></div></Layout>}

function YouTube(){const [query,setQuery]=useState('');const [videos,setVideos]=useState([]);const [url,setUrl]=useState('');const [action,setAction]=useState('summary');const [result,setResult]=useState('');const [question,setQuestion]=useState('');const [busy,setBusy]=useState(false);const searchVideos=async e=>{e.preventDefault();setBusy(true);try{const r=await api.post('/youtube/search',{query});setVideos(r.data.videos);if(!r.data.searchConfigured&&!r.data.videos.length)setResult('YouTube search needs YOUTUBE_API_KEY in backend/.env. You can still paste a video URL below.')}catch(err){setResult(err.response?.data?.error||'Search failed')}finally{setBusy(false)}};const analyze=async()=>{setBusy(true);try{const r=await api.post('/youtube/analyze',{url,action});setResult(r.data.answer)}catch(err){setResult(err.response?.data?.error||'Could not analyze the video')}finally{setBusy(false)}};const ask=async()=>{setBusy(true);try{const r=await api.post('/youtube/ask',{url,question});setResult(r.data.answer)}catch(err){setResult(err.response?.data?.error||'Could not answer the question')}finally{setBusy(false)}};return <Layout><div className="topbar"><div><span className="eyebrow">SUPPLEMENTARY LEARNING</span><h1>YouTube Learning Assistant</h1><p>Find educational videos or paste a YouTube URL with accessible captions.</p></div></div><div className="youtube-grid"><div className="yt-card"><form onSubmit={searchVideos} className="search-form"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a topic, e.g. AVL tree rotations"/><button className="primary">Search</button></form><div className="video-list">{videos.map(v=><button className="video" key={v.videoId} onClick={()=>setUrl(v.url)}>{v.thumbnail&&<img src={v.thumbnail}/>}<div><b>{v.title}</b><span>{v.channel}</span></div></button>)}</div></div><div className="yt-card analyzer"><h2>Analyze a video</h2><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Paste YouTube URL"/><div className="action-row">{[['summary','Summary'],['notes','Complete Notes'],['questions','Key Concepts']].map(x=><button key={x[0]} className={action===x[0]?'selected':''} onClick={()=>setAction(x[0])}>{x[1]}</button>)}</div><button className="primary full" onClick={analyze} disabled={busy}>{busy?'Analyzing...':'Analyze Video'}</button><hr/><h3>Ask a doubt</h3><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="e.g. Explain RR rotation from this video"/><button className="secondary full" onClick={ask} disabled={busy}>Ask from Video</button>{result&&<article className="result"><b>IntelliLearn AI</b>{result.split('\n').map((x,i)=><p key={i}>{x||' '}</p>)}</article>}</div></div></Layout>}

function App(){return <Routes><Route path="/login" element={<Auth mode="login"/>}/><Route path="/register" element={<Auth mode="register"/>}/><Route path="/dashboard" element={<Protected><Dashboard/></Protected>}/><Route path="/faculty" element={<Protected role="faculty"><Faculty/></Protected>}/><Route path="/youtube" element={<Protected><YouTube/></Protected>}/><Route path="*" element={<Redirect/>}/></Routes>}
function Protected({children,role}){const u=user();if(!u)return <Redirect to="/login"/>;if(role&&u.role!==role)return <Redirect to="/dashboard"/>;return children}
function Redirect({to}){const nav=useNavigate();useEffect(()=>nav(to|| (user()?'/dashboard':'/login'),{replace:true}),[]);return null}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>)
